blank_issues_enabled: false
contact_links:
  - name: VATCAR Website
    url: https://vatcar.net
    about: Visit the official VATCAR website
  - name: VATSIM Caribbean Division GitHub
    url: https://github.com/VATSIM-CARIBBEAN
    about: View other VATSIM Caribbean projects
